// Automatically generated by MockGen. DO NOT EDIT!
// Source: http-client.go

package main

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of HttpOperations interface
type MockHttpOperations struct {
	ctrl     *gomock.Controller
	recorder *_MockHttpOperationsRecorder
}

// Recorder for MockHttpOperations (not exported)
type _MockHttpOperationsRecorder struct {
	mock *MockHttpOperations
}

func NewMockHttpOperations(ctrl *gomock.Controller) *MockHttpOperations {
	mock := &MockHttpOperations{ctrl: ctrl}
	mock.recorder = &_MockHttpOperationsRecorder{mock}
	return mock
}

func (_m *MockHttpOperations) EXPECT() *_MockHttpOperationsRecorder {
	return _m.recorder
}

func (_m *MockHttpOperations) Get(url string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Get", url)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockHttpOperationsRecorder) Get(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0)
}
